name: Reduce README
on:
  push:
    paths:
    - _asciidoc_/*.adoc
    branches: ['**']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Install Asciidoctor Reducer
      run: sudo gem install asciidoctor-reducer:1.0.5
    - name: Reduce README
      # to preserve preprocessor conditionals, add the --preserve-conditionals option
      run: asciidoctor-reducer -o _asciidoc_/sample.adoc _asciidoc_/sample_include.adoc
    - name: Commit and Push README
      uses: EndBug/add-and-commit@v9
      with:
        add: _asciidoc_/sample.adoc
